server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
